In [1]:
import numpy as np
import os
import librosa
from pydub import AudioSegment
from pydub.playback import play

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import librosa.display
import plotly.express as px
from pydub import AudioSegment
import sys
import cv2

In [2]:
name_bird = []
for root, dirs, files in os.walk('Traindata/Audio/'):
    if root == 'Traindata/Audio/':
        name_bird = dirs
path_name = []
path_name_list = []
for i in range(len(name_bird)):
    for root, dirs, files in os.walk("Traindata/Audio/"+name_bird[i]):
        for file in files:
            if file.endswith(".mp3"):
                path_name.append(os.path.join(root, file))
    path_name_list.append(path_name)
    path_name = []

In [23]:
def splitSignal(sig, rate, seconds, overlap, minlen):

    # Split signal with overlap
    sig_splits = []
    for i in range(0, len(sig), int((seconds - overlap) * rate)):
        split = sig[i:i + int(seconds * rate)]

        # End of signal?
        if len(split) < int(minlen * rate):
            break
        
        # Signal chunk too short?
        if len(split) < int(rate * seconds):
            split = np.hstack((split, np.zeros((int(rate * seconds) - len(split),))))
        
        sig_splits.append(split)

    return sig_splits

In [103]:
sig, rate = librosa.load(path_name_list[0][0])

/Users/givee/anaconda3/lib/python3.7/site-packages/librosa/core/audio.py:161: UserWarning:

PySoundFile failed. Trying audioread instead.



In [72]:
path_name_list[0][0]

'Traindata/Audio/Patagioenas plumbea_Plumbeous Pigeon/XC227315.mp3'

In [104]:
sig_splits = splitSignal(sig, rate, 5, 1, 1)

In [105]:
sig_splits

[array([-0.00696294, -0.00989491, -0.0065751 , ...,  0.01139491,
         0.00338931,  0.00159741], dtype=float32),
 array([-0.00387561,  0.00229401,  0.00193263, ..., -0.01871327,
        -0.01444266, -0.00971275], dtype=float32),
 array([-0.00506774, -0.01119469, -0.00583129, ...,  0.00990618,
         0.00543443,  0.00084763], dtype=float32),
 array([ 0.0015109 , -0.00709668, -0.00429201, ...,  0.00324483,
        -0.00215083, -0.01279025], dtype=float32),
 array([-0.00118924, -0.01006333, -0.00995998, ..., -0.00752547,
        -0.00301993,  0.00126465], dtype=float32),
 array([-0.01054199, -0.01313993, -0.01314385, ..., -0.02408776,
        -0.02185885, -0.01791646], dtype=float32),
 array([-0.0128127 , -0.01008504, -0.01047143, ..., -0.00466011,
        -0.0078342 , -0.0032389 ], dtype=float32),
 array([ 0.00030933, -0.00124392, -0.01063262, ...,  0.        ,
         0.        ,  0.        ])]

In [106]:
def randomposit(sig_splits):
    list_count = []
    sig_splits_new = []
    count = len(sig_splits)
    for i in range(count):
        index = np.random.randint(len(sig_splits))
        sig_splits_new.append(sig_splits[index])
        list_count.append(index)
        sig_splits.pop(index)
    sig_splits = splitSignal(sig, rate, 5, 1, 1)
    return sig_splits_new, sig_splits

In [107]:
sig_splits_new, sig_splits = randomposit(sig_splits)

8
8
8
8
8
8
8
8


In [108]:
sig_splits_new

[array([ 0.0015109 , -0.00709668, -0.00429201, ...,  0.00324483,
        -0.00215083, -0.01279025], dtype=float32),
 array([-0.00387561,  0.00229401,  0.00193263, ..., -0.01871327,
        -0.01444266, -0.00971275], dtype=float32),
 array([-0.0128127 , -0.01008504, -0.01047143, ..., -0.00466011,
        -0.0078342 , -0.0032389 ], dtype=float32),
 array([-0.00506774, -0.01119469, -0.00583129, ...,  0.00990618,
         0.00543443,  0.00084763], dtype=float32),
 array([-0.01054199, -0.01313993, -0.01314385, ..., -0.02408776,
        -0.02185885, -0.01791646], dtype=float32),
 array([-0.00696294, -0.00989491, -0.0065751 , ...,  0.01139491,
         0.00338931,  0.00159741], dtype=float32),
 array([-0.00118924, -0.01006333, -0.00995998, ..., -0.00752547,
        -0.00301993,  0.00126465], dtype=float32),
 array([ 0.00030933, -0.00124392, -0.01063262, ...,  0.        ,
         0.        ,  0.        ])]

In [109]:
sig_splits

[array([-0.00696294, -0.00989491, -0.0065751 , ...,  0.01139491,
         0.00338931,  0.00159741], dtype=float32),
 array([-0.00387561,  0.00229401,  0.00193263, ..., -0.01871327,
        -0.01444266, -0.00971275], dtype=float32),
 array([-0.00506774, -0.01119469, -0.00583129, ...,  0.00990618,
         0.00543443,  0.00084763], dtype=float32),
 array([ 0.0015109 , -0.00709668, -0.00429201, ...,  0.00324483,
        -0.00215083, -0.01279025], dtype=float32),
 array([-0.00118924, -0.01006333, -0.00995998, ..., -0.00752547,
        -0.00301993,  0.00126465], dtype=float32),
 array([-0.01054199, -0.01313993, -0.01314385, ..., -0.02408776,
        -0.02185885, -0.01791646], dtype=float32),
 array([-0.0128127 , -0.01008504, -0.01047143, ..., -0.00466011,
        -0.0078342 , -0.0032389 ], dtype=float32),
 array([ 0.00030933, -0.00124392, -0.01063262, ...,  0.        ,
         0.        ,  0.        ])]

In [ ]:
namesound00 = path_name_list[0][0].split('/')

In [ ]:
plt.figure()
plt.subplot(3, 1, 1)
librosa.display.waveplot(sig_splits[0])
plt.title(namesound00[-2]+' '+namesound00[-1] + ' Section 0')


plt.subplot(3,1,2)
#y, sr = librosa.load(path_name_list[0][1])
librosa.display.waveplot(sig_splits[4])
plt.title(namesound00[-2]+' '+namesound00[-1] + ' Section 4')

plt.subplot(3, 1, 3)
librosa.display.waveplot(sig_splits[6])
plt.title(namesound00[-2]+' '+namesound00[-1] + ' Section 6')

plt.tight_layout()

In [39]:
for sig in sig_splits:
    spec = get_spec(sig, rate, (128, 256))

NameError: name 'get_spec' is not defined

In [ ]:
def stft(sig, rate, shape=(128, 256), fmin=500, fmax=15000, normalize=True):

    # shape = (height, width) in pixels

    # STFT-Spec parameters
    N_FFT = int((rate * shape[0] * 2) / abs(fmax - fmin)) + 1
    P_MIN = int(float(N_FFT / 2) / rate * fmin) + 1
    P_MAX = int(float(N_FFT / 2) / rate * fmax) + 1    
    HOP_LEN = len(sig) // (shape[1] - 1)

    # Librosa stft-spectrum
    spec = librosa.core.stft(sig, hop_length=HOP_LEN, n_fft=N_FFT, window='hamm')

    # Convert power spec to dB scale (compute dB relative to peak power)
    spec = librosa.amplitude_to_db(librosa.core.magphase(spec)[0], ref=np.max, top_db=80)

    # Trim to desired shape using cutoff frequencies
    spec = spec[P_MIN:P_MAX, :shape[1]]

    # Flip spectrum vertically (only for better visialization, low freq. at bottom)
    spec = spec[::-1, ...]    

    # Normalize values between 0 and 1
    if normalize:
        spec -= spec.min()
        if not spec.max() == 0:
            spec /= spec.max()
        else:
            spec = np.clip(spec, 0, 1)    
    
    return spec.astype('float32')

In [ ]:
def get_spec(sig, rate, shape, spec_type='linear', **kwargs):

    if spec_type.lower()== 'melspec':
        return melspec(sig, rate, shape, **kwargs)
    else:
        return stft(sig, rate, shape, **kwargs)

In [ ]:
spec